### ISSUE TITLE
Improve alignment and spacing of text

### ISSUE THREAD

**Issue by LiteracyFanatic** [oknozor/onagre#14]
Nice project! I think it would look nicer if the text was vertically centered and there was a small margin between it and the icons.

**Comment by oknozor** [comment]
@LiteracyFanatic I agree, ideally this would be exposed in the theme config. I'll work on this as soon as possible.

**Comment by oknozor** [comment]
This was quite straight forward actually. 
You can update right now :) 

[![screenshot-2020-11-22-T15-19-17-0100.png](https://i.postimg.cc/QtBK7ymB/screenshot-2020-11-22-T15-19-17-0100.png)](https://postimg.cc/sQr2dKty)
