### ISSUE TITLE
Onagre doesn't scroll view when navigating with arrow keys

### ISSUE THREAD

**Issue by poperigby** [oknozor/onagre#15]
When scrolling with the arrow keys, the view doesn't scroll along with the focused item. The view scrolls just fine when using the mouse wheel.

OS: Arch Linux
WM: Sway

**Comment by oknozor** [comment]
Thank you for pointing that out. 
I am well aware of the issue, I am waiting for [this PR](https://github.com/hecrj/iced/pull/607) to be merged in iced. 
Once its done, this would be trivial to implement.
