### ISSUE TITLE
Question regarding the popshell dependency

### ISSUE THREAD

**Issue by VarLad** [oknozor/onagre#38]
Do we really need popshell for onagre?
How much work would it be to completely remove popshell from the deps?

**Comment by oknozor** [comment]
Hello @VarLad 

Onagre is not using pop-shell, it's using pop-launcher. 

The first implementation of onagre was dependency free but using [pop-launcher](https://github.com/pop-os/launcher) allow to focus on the user experience and the UI rather that reinventing the wheel (see #19).  

Maintaining the whole freedesktop specification implementations is a tedious and boring task. It add a big pile of code that already exist out there, solving problems that have already been solved by other engineers. 
I have neither the time nor the desire to do that again. 

- Pop-launcher is used by many pop OS users and maintained by experienced engineers working for one of the most popular linux distro. 
- They are open to contribution so we are not locked with the current state of pop-launcher. 
- Pop-launcher is extensible and we can build plugin if we need more feature in onagre

I really don't think getting rid of it would be a good idea.

**Comment by VarLad** [comment]
I'm not *against* using pop-launcher, but I don't think there's an easy way for me to install it :)

**Comment by VarLad** [comment]
There's https://copr.fedorainfracloud.org/coprs/carlwgeorge/cosmic/ which says it has plans to implement pop-launcher
Lets see how long it takes

**Comment by oknozor** [comment]
Meanwhile you can try to install it from source, there is a makefile if I remember correctly
