### ISSUE TITLE
question: Why use pop-launcher?

### ISSUE THREAD

**Issue by colemickens** [oknozor/onagre#44]
**Describe the bug**

Hi, what is the purpose of using pop-launcher versus systemctl/dbus for launching?

Thanks!

**Comment by oknozor** [comment]
You can take a look at #38 and #19. 
I admit the name can be confusing but pop-launcher is not used only for launching only.
It has the free-desktop entry specification sorted out already, i.e searching, launching, sorting desktop entry. 
It also provides a set of builtin plugin and can be easily extended with user defined plugin.
