### ISSUE TITLE
feedback: Tried Onagre on Fedora Silverblue

### ISSUE THREAD

**Issue by manan-gup** [oknozor/onagre#54]
Hey,
Sorry to spam your issues but didn't know how else to leave feedback.

I use Fedora Silverblue (which is an immutable OS in case someone doesn't know) so most applications are either installed as Flatpaks or inside Distrobox/Toolbox containers (running on podman). I successfully installed Onagre inside a Fedora container and the files plugin worked as expected. But there's no way to open the flatpak apps installed on the base system from inside the container. And I don't want to overlay all the build tools required on my base system. So, I'll give it a pass for now but I did like a lot what I could use. I'll definitely give it another shot if it ever gets packaged for Fedora. Here's a Gruvbox inspired theme I threw together :)

<img src="https://user-images.githubusercontent.com/77879361/208198515-816ae345-37a7-435f-88dc-b0a4e7c24518.png" width=400 alt="Screenshot of Onagre in Gruvbox colours" />

P.S. `cmake` is required as a dependency to build Onagre but isn't mentioned in the Readme.

**Comment by oknozor** [comment]
Hello @manan-gup thanks for your interest. Flatpak is not supported yet (see: #33). I don't have time to work on this right now but PRs are welcome.
