### ISSUE TITLE
How to setup desktop short-cuts 

### ISSUE THREAD

**Issue by Aviksaikat** [oknozor/onagre#65]
How can we set up short cuts to launch? is there anything like `ctrl+space` ? 
How can we set themes

**Comment by oknozor** [comment]
> How can we set up short cuts to launch? is there anything like ctrl+space ?

What do you mean by `ctrl+space` ? 

>  How can we set themes

https://github.com/oknozor/onagre/wiki/Theming

**Comment by Aviksaikat** [comment]
shortcut to launch it

**Comment by oknozor** [comment]
What operating system/desktop environment are you using ?

**Comment by Aviksaikat** [comment]
`Linux kali 6.5.0-kali3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.6-1kali1 (2023-10-09) x86_64 GNU/Linux`

**Comment by oknozor** [comment]
Well you should configure a keyboard shortcut according to that specific distro documentations to launch `onagre`.

**Comment by Aviksaikat** [comment]
how the `.desktop` file should look like ?

**Comment by oknozor** [comment]
like any other: 
`Exec=onagre`

That said I would use a shortcut rather than a desktop entry.
